"""
Django settings for public_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import re
import os
import inspect
import logging
from pathlib import Path
from dotenv import load_dotenv
from cryptography.fernet import Fernet
import base64

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
"""
SECRET_KEY = os.getenv("SECRET_KEY")

# Open AI
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

PAYPAL_MODE = os.getenv("PAYPAL_MODE", "production")
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
PAYPAL_REDIRECT_URI = os.getenv("PAYPAL_REDIRECT_URI")
PAYPAL_BASE_URL = os.getenv("PAYPAL_BASE_URL")
PAYPAL_COMMISSION_RATE = float(os.getenv("PAYPAL_COMMISSION_RATE", 0.10))
MONTHLY_SUBSCRIPTION_PRICE = float(os.getenv("MONTHLY_SUBSCRIPTION_PRICE", 9.99))
YEARLY_SUBSCRIPTION_PRICE = float(os.getenv("YEARLY_SUBSCRIPTION_PRICE", 99.99))
PAYPAL_MONTHLY_PLAN_ID = os.getenv("PAYPAL_MONTHLY_PLAN_ID")
PAYPAL_ANNUAL_PLAN_ID = os.getenv("PAYPAL_ANNUAL_PLAN_ID")
"""
# =========================
# DEVELOPMENT SETTINGS
# =========================

DEBUG = True

if not DEBUG:
    ALLOWED_HOSTS = ["fancylearn.com"]
    
ALLOWED_HOSTS = ["fancylearn.com", "127.0.0.1", "localhost"]

INTERNAL_IPS = ["127.0.0.1"]

WHITELISTED_IPS = [
    "127.0.0.1",
    "::1",
]

MAINTENANCE_MODE = False


# ❌ DISABLE HTTPS IN DEV
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# =========================
# Production SETTINGS
# =========================

#ALLOWED_HOSTS = ["fancylearn.com"]

#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

#SECURE_HSTS_SECONDS = 31536000
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'widget_tweaks',
    "social_django",
    'MindBridge',
]

AUTH_USER_MODEL = "MindBridge.User"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # =========================
    # Custom Middleware (your system)
    # =========================
    'MindBridge.middleware.RedirectNonExistingURLsMiddleware',
    'MindBridge.middleware.AdminAccessMiddleware',
    'MindBridge.middleware.MaintenanceModeMiddleware',
    'MindBridge.middleware.ContentSecurityPolicyMiddleware',
    'MindBridge.middleware.SecureHeadersMiddleware',
    'MindBridge.middleware.IgnoreBrokenPipeMiddleware',
    'MindBridge.middleware.RecurringAdsMiddleware',
    
]

ROOT_URLCONF = 'public_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MindBridge.context_processors.sidebar_data',
                "MindBridge.context_processors.subscription_status",
                "MindBridge.context_processors.ads_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'public_project.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'OPTIONS': {
       'timeout': 30,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")
ADMIN_NAME = os.getenv("ADMIN_NAME")


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv("VAPID_PUBLIC_KEY"),
    "VAPID_PRIVATE_KEY": os.getenv("VAPID_PRIVATE_KEY"),
    "VAPID_ADMIN_EMAIL": f"mailto:{os.getenv('ADMIN_EMAIL')}",
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ----------------- STATIC FILES -----------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # optional if you have a global static folder
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic will copy files here

# ----------------- MEDIA FILES -----------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}