# Generated by Django 5.2.4 on 2026-03-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Farming', 'Farming'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Environment', 'Environment'), ('Finance', 'Finance'), ('Technology', 'Technology')], max_length=100, unique=True),
        ),
    ]
