# Generated by Django 5.2.4 on 2026-03-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0003_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='MindBridge.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Farming', 'Farming'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Environment', 'Environment'), ('Finance', 'Finance'), ('Technology', 'Technology')], max_length=100, unique=True),
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
