# Generated by Django 5.2.4 on 2026-03-07 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0004_alter_advertisement_category_alter_problem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
