# Generated by Django 5.2.4 on 2026-03-07 15:04

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problem_media/', validators=[MindBridge.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problem_media/', validators=[MindBridge.models.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='ProblemMedia',
        ),
    ]
