# Generated by Django 5.2.4 on 2026-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0006_answer_file_problem_file_delete_problemmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Farming', 'Farming'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Environment', 'Environment'), ('Finance', 'Finance'), ('Technology', 'Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problem_media/'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for this problem', max_length=250),
        ),
    ]
