# Generated by Django 5.2.4 on 2026-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0008_alter_follow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tips_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
