# Generated by Django 5.2.4 on 2026-03-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0009_problem_tips_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MindBridge.problem'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MindBridge.answer'),
        ),
    ]
