# Generated by Django 5.2.4 on 2026-03-14 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0012_event_eventinvitation_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='live_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='MindBridge.event')),
            ],
        ),
    ]
