# Generated by Django 5.2.4 on 2026-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0013_eventrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
