# Generated by Django 5.2.4 on 2026-03-15 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0014_event_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Technology', 'Technology'), ('Software Development', 'Software Development'), ('Cybersecurity', 'Cybersecurity'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('DevOps', 'DevOps'), ('Agriculture', 'Agriculture'), ('Farming', 'Farming'), ('Food Production', 'Food Production'), ('Fisheries', 'Fisheries'), ('Forestry', 'Forestry'), ('Healthcare', 'Healthcare'), ('Medicine', 'Medicine'), ('Public Health', 'Public Health'), ('Mental Health', 'Mental Health'), ('Pharmacy', 'Pharmacy'), ('Education', 'Education'), ('E-learning', 'E-learning'), ('Research', 'Research'), ('Academic Support', 'Academic Support'), ('Environment', 'Environment'), ('Climate Change', 'Climate Change'), ('Renewable Energy', 'Renewable Energy'), ('Sustainability', 'Sustainability'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Banking', 'Banking'), ('Investments', 'Investments'), ('Cryptocurrency', 'Cryptocurrency'), ('Insurance', 'Insurance'), ('Business', 'Business'), ('Entrepreneurship', 'Entrepreneurship'), ('Startups', 'Startups'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Law', 'Law'), ('Legal Advice', 'Legal Advice'), ('Government', 'Government'), ('Public Policy', 'Public Policy'), ('Engineering', 'Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Construction', 'Construction'), ('Architecture', 'Architecture'), ('Real Estate', 'Real Estate'), ('Transportation', 'Transportation'), ('Logistics', 'Logistics'), ('Automotive', 'Automotive'), ('Aviation', 'Aviation'), ('Media', 'Media'), ('Journalism', 'Journalism'), ('Photography', 'Photography'), ('Film & Video', 'Film & Video'), ('Arts', 'Arts'), ('Music', 'Music'), ('Design', 'Design'), ('Graphic Design', 'Graphic Design'), ('Sports', 'Sports'), ('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Tourism', 'Tourism'), ('Hospitality', 'Hospitality'), ('Travel', 'Travel'), ('Retail', 'Retail'), ('E-commerce', 'E-commerce'), ('Customer Service', 'Customer Service'), ('Social Issues', 'Social Issues'), ('Community Development', 'Community Development'), ('Nonprofit', 'Nonprofit'), ('Human Rights', 'Human Rights')], max_length=100),
        ),
        migrations.CreateModel(
            name='PayPalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paypal_email', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
