# Generated by Django 5.2.4 on 2026-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0015_alter_problem_category_paypalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('awarded', 'Awarded'), ('refunded', 'Refunded')], default='held', max_length=20),
        ),
    ]
