# Generated by Django 5.2.4 on 2026-03-16 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0016_bounty_paypal_order_id_bounty_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemPromotion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('promotion_type', models.CharField(choices=[('featured', 'Featured 24h'), ('boosted', 'Boosted 3 Days'), ('pinned', 'Pinned Homepage')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='MindBridge.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
