# Generated by Django 5.2.4 on 2026-03-17 10:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0019_alter_advertisement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 10, 22, 14, 847743, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
