# Generated by Django 5.2.4 on 2026-03-17 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0020_alter_advertisement_options_advertisement_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='active',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
