# Generated by Django 5.2.4 on 2026-03-18 20:09

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0021_remove_advertisement_active_advertisement_advertiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='problem_media/', validators=[MindBridge.models.validate_file_size]),
        ),
    ]
