# Generated by Django 5.2.4 on 2026-03-18 20:13

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0022_alter_problem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='ads/', validators=[MindBridge.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='eventrecording',
            name='file',
            field=models.FileField(upload_to='live_recordings/', validators=[MindBridge.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[MindBridge.models.validate_file_size]),
        ),
    ]
