# Generated by Django 5.2.4 on 2026-03-22 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0023_alter_advertisement_image_alter_eventrecording_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindBridge.answer')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kb_entry', to='MindBridge.problem')),
            ],
        ),
    ]
