# Generated by Django 5.2.4 on 2026-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0024_knowledgebaseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationlog',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
