# Generated by Django 5.2.4 on 2026-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0025_reputationlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='post_type',
            field=models.CharField(choices=[('issue', 'Issue'), ('information', 'Information')], default='issue', help_text='Select whether this post is an issue or information', max_length=20),
        ),
    ]
