# Generated by Django 5.2.4 on 2026-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0026_problem_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
