# Generated by Django 5.2.4 on 2026-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0027_answer_is_flagged_answer_moderation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
