# Generated by Django 5.2.4 on 2026-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0030_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='post_type',
            field=models.CharField(choices=[('issue', 'Report an Issue'), ('information', 'Share an Idea')], default='issue', help_text='Select whether this post is an issue or information', max_length=20),
        ),
    ]
