# Generated by Django 5.2.4 on 2026-04-18 14:12

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0033_eventreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhub',
            name='meeting_url',
            field=models.URLField(blank=True, validators=[MindBridge.models.validate_safe_meeting_url]),
        ),
    ]
