# Generated by Django 5.2.4 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0034_alter_eventhub_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_reason',
            field=models.CharField(blank=True, choices=[('fix_bug', 'Fix bug'), ('consultation', 'Consultation'), ('session', 'Live session'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability_status',
            field=models.CharField(choices=[('online', 'Available now'), ('later', 'Available later'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('tip', 'Tip'), ('bounty', 'Bounty'), ('subscription', 'Subscription'), ('ad', 'Advertisement'), ('booking', 'Booking')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['availability_status'], name='MindBridge__availab_dbc3b6_idx'),
        ),
    ]
