# Generated by Django 5.2.4 on 2026-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0035_userprofile_availability_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_mode',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote')], db_index=True, default='remote', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['availability_mode'], name='MindBridge__availab_4fd69e_idx'),
        ),
    ]
