# Generated by Django 5.2.4 on 2026-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0036_userprofile_availability_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability_mode',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('not determined', 'Not determined')], db_index=True, default='remote', max_length=20),
        ),
    ]
