# Generated by Django 5.2.4 on 2026-04-29 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0038_livesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='provider',
            field=models.CharField(choices=[('meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams')], default='meet', max_length=10),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions_as_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('ended', 'Ended')], default='created', max_length=10),
        ),
    ]
