# Generated by Django 5.2.4 on 2026-04-30 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0040_availabilityslot_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
