# Generated by Django 5.2.4 on 2026-04-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0041_alter_availabilityslot_id_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
