# Generated by Django 5.2.4 on 2026-04-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0045_alter_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='is_booked',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('slot',), name='unique_active_booking_per_slot'),
        ),
    ]
