# Generated by Django 5.2.4 on 2026-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0046_remove_availabilityslot_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
