# Generated by Django 5.2.4 on 2026-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0047_availabilityslot_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
