# Generated by Django 5.2.4 on 2026-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0048_availabilityslot_currency_availabilityslot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='unit',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('session', 'Per Session')], default='hour', max_length=20),
        ),
    ]
