# Generated by Django 5.2.4 on 2026-05-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0052_review_user_rating_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='rating_between_1_and_5',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='MindBridge__rating_0c7b0a_idx',
        ),
    ]
