# Generated by Django 5.2.4 on 2026-05-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0053_remove_review_rating_between_1_and_5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
