# Generated by Django 5.2.4 on 2026-05-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0055_userreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='resolved',
        ),
        migrations.AlterField(
            model_name='userreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
