# Generated by Django 5.2.4 on 2026-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0056_alter_userreport_options_remove_userreport_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(db_index=True, default='Ad Description'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, default='Ad Title', max_length=255),
        ),
    ]
