# Generated by Django 5.2.4 on 2026-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0058_rename_category_advertisement_related_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='next_relaunch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='recurring_every',
            field=models.PositiveIntegerField(blank=True, choices=[(3, 'Every 3 Days'), (7, 'Every 7 Days'), (14, 'Every 14 Days'), (30, 'Every 30 Days')], null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='relaunch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='stop_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=10),
        ),
    ]
