# Generated by Django 5.2.4 on 2026-05-12 14:29

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0061_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='promos/', validators=[MindBridge.models.validate_file_size]),
        ),
    ]
