# Generated by Django 5.2.4 on 2026-05-13 18:58

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0062_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='promos/', validators=[MindBridge.models.validate_ad_file_size]),
        ),
    ]
