# Generated by Django 5.2.4 on 2026-05-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0063_alter_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='ads_file',
        ),
    ]
