# Generated by Django 5.2.4 on 2026-05-13 19:33

import MindBridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0064_rename_image_advertisement_ads_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ads_file',
            field=models.FileField(upload_to='promos/', validators=[MindBridge.models.validate_ad_file_size]),
        ),
    ]
