# Generated by Django 5.2.4 on 2026-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0065_alter_advertisement_ads_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
