# Generated by Django 5.2.4 on 2026-05-19 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0066_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 15, 30, 6, 725908, tzinfo=datetime.timezone.utc)),
        ),
    ]
