# Generated by Django 5.2.4 on 2026-05-25 10:34

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0067_emailotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 25, 10, 38, 55, 725219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CreatorsSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paypal_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('APPROVAL_PENDING', 'Approval Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='APPROVAL_PENDING', max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_time', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreatorSubscription',
        ),
        migrations.AddConstraint(
            model_name='creatorssubscription',
            constraint=models.UniqueConstraint(fields=('creator', 'subscriber'), name='unique_creator_subscription'),
        ),
    ]
