# Generated by Django 5.2.4 on 2026-05-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0068_alter_emailotp_expires_at_creatorssubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verification_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 26, 19, 15, 55, 95692, tzinfo=datetime.timezone.utc)),
        ),
    ]
