# Generated by Django 5.2.4 on 2026-05-28 19:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0069_userprofile_is_verification_recurring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatorssubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Premium Subscription', 'verbose_name_plural': 'Premium Subscriptions'},
        ),
        migrations.RemoveConstraint(
            model_name='creatorssubscription',
            name='unique_creator_subscription',
        ),
        migrations.RemoveField(
            model_name='creatorssubscription',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='creatorssubscription',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='creatorssubscription',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='plan',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='premium_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorssubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorssubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creatorssubscription',
            name='paypal_plan_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creatorssubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creatorssubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='creatorssubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 28, 19, 10, 15, 41082, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='creatorssubscription',
            index=models.Index(fields=['user'], name='MindBridge__user_id_c6fd19_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorssubscription',
            index=models.Index(fields=['status'], name='MindBridge__status_ada122_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorssubscription',
            index=models.Index(fields=['paypal_subscription_id'], name='MindBridge__paypal__0f1345_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorssubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_active_subscription_per_user'),
        ),
    ]
