# Generated by Django 5.2.4 on 2026-06-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0070_alter_creatorssubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_expiring_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_urgent_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 8, 52, 26, 236503, tzinfo=datetime.timezone.utc)),
        ),
    ]
