# Generated by Django 5.2.4 on 2026-06-13 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindBridge', '0071_advertisement_is_expiring_soon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 11, 53, 55, 990631, tzinfo=datetime.timezone.utc)),
        ),
    ]
